routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, render_template_string
from extensions import db, bcrypt, login_manager
from models import User, Part, Job
from forms import RegisterForm, LoginForm, PasswordResetRequestForm, PasswordResetForm, JobDataForm, NewPartForm
from flask_login import login_user, login_required, logout_user, current_user
from flask_mailman import EmailMessage
from reset_pass_html_content import email_html_content


main = Blueprint("main", __name__)

##### Application Routing (General) #####

# @app.route('/')
# def home():
#     return render_template('home.html')


# Home Screen is Log In (for now - if there is any public info, create a public dash w a login option)
@main.route('/', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)

                # admin user
                if user.role == "admin":
                    return redirect(url_for("main.admin_dash"))

                # regular user
                if user.role == "user":
                    return redirect(url_for("main.user_dash"))

    return render_template('auth/login.html', form=form)


@main.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))


@main.route('/job_data', methods=['GET', 'POST'])
@login_required
def job_data():
    parts = Part.query.all()
    part_choices = [(str(p.id), p.part_name) for p in parts]
    form = JobDataForm()
    form.part_id.choices = part_choices
    if request.method == 'POST':
        # get data from hidden form
        part_id = request.form.get('part_id')
        num_batches = int(request.form.get('num_batches'))
        num_per_batch = int(request.form.get('num_per_batch'))
        task = request.form.get('task')
        paint_type = request.form.get('paint_type')
        total_time = float(request.form.get('total_time'))
        avg_time_per_batch = float(request.form.get('avg_time_per_batch'))
        avg_time_per_part = float(request.form.get('avg_time_per_part'))

        # get part name
        part = Part.query.get(part_id)
        part_name = part.part_name if part else None

        # save data to Job table
        new_job = Job(
            user_id=current_user.id,
            part_id=part_id,
            part_name=part_name,
            num_batches=num_batches,
            num_per_batch=num_per_batch,
            task=task,
            paint_type=paint_type,
            total_time=total_time,
            avg_time_per_batch=avg_time_per_batch,
            avg_time_per_part=avg_time_per_part
        )
        db.session.add(new_job)
        db.session.commit()
        flash("Job data saved!")
        if current_user.role == "admin":
            return redirect(url_for('main.admin_dash'))
        return redirect(url_for('main.user_dash'))
    return render_template('data/job_data.html', form=form)


###### Request and Reset Password ######
def send_reset_password_email(user):
    # create reset password url with unique token
    reset_pass_url = url_for('main.reset_password',
                             token=user.generate_password_token(),
                             user_id=user.id,
                             _external=True)
    # create email message containing special url
    email_body = render_template_string(email_html_content,
                                        reset_pass_url=reset_pass_url)
    msg = EmailMessage(subject="Password Reset",
                       body=email_body,
                       to=[user.email])
    msg.content_subtype = "html"
    # sends message to email address input by user
    msg.send()


@main.route("/request_new_pass", methods=['GET', 'POST'])
def request_new_pass():
    form = PasswordResetRequestForm()
    # check if email corresponds to an existing user...

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # if so, send password reset link
        if user:
            send_reset_password_email(user)

        # direct user to check email for link
        flash("Instructions to reset your password were sent to your email address, if it exists in our system.")

        return redirect(url_for("main.request_new_pass"))

    return render_template('auth/request_new_pass.html', form=form)


@main.route('/reset_password/<token>/<int:user_id>', methods=['GET', 'POST'])
def reset_password(token, user_id):
    # validate password reset token
    user = User.validate_reset_pass_token(token, user_id)
    #   error if unable to validate
    if user is None:
        return render_template('reset_pass_error.html')
    # take new password from form; hash password; update database
    form = PasswordResetForm()

    if form.validate_on_submit():
        # create hash encoding for new password and update user database with this value
        hashed_new_password = bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_new_password
        db.session.commit()
        return render_template('reset_pass_success.html')

    # reset password page (pre submission)
    return render_template('auth/reset_password.html', form=form)


##### Application Routing (User Features) #####


@main.route('/user_dash', methods=['GET', 'POST'])
@login_required
def user_dash():
    return render_template('dash/user_dash.html')


##### Application Routing (Admin Features) #####
@main.route('/admin_dash', methods=['GET', 'POST'])
@login_required
def admin_dash():
    if current_user.role != "admin":
        flash("Access denied.")
        return redirect(url_for('main.user_dash'))
    return render_template('dash/admin_dash.html')


@main.route('/register', methods=['GET', 'POST'])
@login_required
def register():
    if current_user.role != "admin":
        flash("Access denied.")
        return redirect(url_for('main.user_dash'))
    form = RegisterForm()

    # create new user in database
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        new_user = User(first=form.first.data,
                        last=form.last.data,
                        email=form.email.data,
                        username=form.username.data,
                        password=hashed_password,
                        role=form.role.data)
        db.session.add(new_user)
        db.session.commit()
        # redirect to list of users
        return redirect(url_for("main.overview_data"))

    return render_template('auth/register.html', form=form)


@main.route('/new_part', methods=['GET', 'POST'])
@login_required
def new_part():
    if current_user.role != "admin":
        flash("Access denied.")
        return redirect(url_for('main.user_dash'))

    form = NewPartForm()

    # create new part to add to Part table
    if form.validate_on_submit():
        new_part = Part(part_name=form.part_name.data,
                        surface_area=form.surface_area.data)
        db.session.add(new_part)
        db.session.commit()
        # redirect to admin dashboard
        return redirect(url_for("main.admin_dash"))

    return render_template('data/new_part.html', form=form)


@main.route('/overview_data', methods=['GET', 'POST'])
@login_required
def overview_data():
    if current_user.role != "admin":
        flash("Access denied.")
        return redirect(url_for('main.user_dash'))

    users = User.query.all()
    parts = Part.query.all()
    jobs = Job.query.all()
    return render_template('data/overview_data.html', users=users, parts=parts, jobs=jobs)


@main.route('/edit_user/<int:user_id>', methods=['POST'])
@login_required
def edit_user(user_id):
    user = User.query.get_or_404(user_id)
    action = request.form['action']
    if action == "toggle_role":
        user.role = "admin" if user.role == "user" else "user"
    if action == "update_email":
        user.email = request.form["email"]
    db.session.commit()
    return redirect(url_for("main.overview_data"))


@main.route('/estimate', methods=['GET', 'POST'])
@login_required
def estimate():
    if current_user.role != "admin":
        flash("Access denied.")
        return redirect(url_for('main.user_dash'))
    return render_template('data/estimate.html')

templates/data/estimate.html
<!DOCTYPE html>
  <html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estimation Tool</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  </head>

  <body>

    <h1>Estimation Tool</h1>
    
    <a href="{{url_for('main.logout')}}">Click to log out.</a>
    
  </body>

templates/data/job_data.html
<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Collection Tool</title>
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"> -->
    <style>
        #stopwatchSection { display: none; }
        #timerDisplay { font-size: 2em; margin: 10px 0; }
    </style>
</head>
<body>
  
 <h1>Job Data Collection Tool</h1>

 <!-- Form Section -->
 <form method = "POST" action="" id="jobForm">
      {{  form.hidden_tag()  }}

      <label> Part Name: {{ form.part_id() }}</label> <br><br>
      <label> Number of Batches: {{  form.num_batches  }}</label> <br><br>
      <label> Number of Parts per Batch: {{  form.num_per_batch  }} </label> <br><br>
      <label> Task: {{  form.task }} </label> <br><br>
      <label> Paint Type: {{  form.paint_type  }} </label><br><br>
      <button type="button" id="startBtn">Start Job</button>
 </form>

 <!-- Stopwatch Section -->
 <div id ="stopwatchSection">
    <div id = "timerDisplay">00:00:00</div>
    <button type="button" id="nextBatchBtn">Next Batch</button>
    <button type="button" id="finishBtn">Finish</button>
    <div id="lapTimes"></div>

    <!-- Hidden form to submit all data -->
    <form id="finalForm" method="POST" style="display:none;">
        <input type="hidden" name="part_id" id="finalPartId">
        <input type="hidden" name="num_batches" id="finalNumBatches">
        <input type="hidden" name="num_per_batch" id="finalNumPerBatch">
        <input type="hidden" name="task" id="finalTask">
        <input type="hidden" name="paint_type" id="finalPaintType">
        <!--<input type="hidden" name="lap_times" id="finalLapTimes">-->
        <input type="hidden" name="total_time" id="finalTotalTime">
        <input type="hidden" name="avg_time_per_batch" id="finalAvgBatch">
        <input type="hidden" name="avg_time_per_part" id="finalAvgPart">
    </form>

 </div>

 <script>
    // Global Variables
    let lapTimes = [] // store recorded times for each Batch
    let batchCount = 1 // track number of completed batches
    let startTime, timerInterval; // start time of current batch and interval at which timer updates


    // Functions
    function startBatch(){
        startTime = Date.now();
        timerInterval = setInterval(updateTimer, 100);
        document.getElementById('timerDisplay').textContent = "00:00:00";
    }

    function recordLap() {
        let lap = Math.floor((Date.now() - startTime)/1000); // JavaScript records time in milliseconds -- divide by 1000 to measure seconds
        // add lap time to initialized list 
        lapTimes.push(lap);
        // stop timer
        clearInterval(timerInterval);
    }

    function updateTimer(){
        let now = Date.now();
        let elapsed = Math.floor((now - startTime) / 1000);
        let hours = Math.floor(elapsed/3600);
        let minutes = Math.floor((elapsed % 3600) / 60);
        let seconds = elapsed % 60;
        document.getElementById('timerDisplay').textContent =
            `${pad(hours)}:${pad(minutes)}:${pad(seconds)}`;
    }

    function pad(num) {
        // pad string with zeros until it reaches len of 2
        return num.toString().padStart(2, '0');
    }

    // Start Job
    document.getElementById('startBtn').onclick = function() {
        // hide form, show stopwatch
        document.getElementById('jobForm').style.display = "none";
        document.getElementById('stopwatchSection').style.display = "block";
        // reset global variables and start time (maybe)
        // batchCount = 0
        //lapTimes = []
        startBatch()

    };


    // Next Batch
    document.getElementById('nextBatchBtn').onclick = function() {
        recordLap();
        batchCount++;
        startBatch();
    };

    // Finish
    document.getElementById('finishBtn').onclick = function(){
        // record final lap
        recordLap();
        clearInterval(timerInterval);
        console.log("final lap recorded")

        // calculate summary stats (times in sec)

        // total time
        let totalTime = lapTimes.reduce((a,b) => a+b, 0);
        // average time per batch
        let batchTime = totalTime/lapTimes.length;
        // number of parts per batch, total parts, average time per part;
        let batchParts = parseInt(document.getElementById('jobForm').num_per_batch.value);
        let numParts = batchParts * lapTimes.length;
        let partTime = totalTime/numParts;

        // Show lap times
        document.getElementById('lapTimes').textContent = "Lap times (seconds): " + lapTimes.join(", ");

        // Fill hidden form and submit
        document.getElementById('finalPartId').value = document.getElementById('jobForm').part_id.value;
        document.getElementById('finalNumBatches').value = document.getElementById('jobForm').num_batches.value;
        document.getElementById('finalNumPerBatch').value = document.getElementById('jobForm').num_per_batch.value;
        document.getElementById('finalTask').value = document.getElementById('jobForm').task.value;
        document.getElementById('finalPaintType').value = document.getElementById('jobForm').paint_type.value;
        //document.getElementById('finalLapTimes').value = JSON.stringify(lapTimes);
        document.getElementById('finalTotalTime').value = totalTime;
        document.getElementById('finalAvgBatch').value = batchTime;
        document.getElementById('finalAvgPart').value = partTime;
        console.log("Submitting form...");
        document.getElementById('finalForm').submit();
    };



 </script>     
</body>
</html>

templates/data/new_part.html
<!DOCTYPE html>
  <html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Part Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  </head>

  <body>

    <h1>Add a New Part</h1>
    <form method = "POST" action="">
      {{  form.hidden_tag()  }}

      {{  form.part_name  }} <br><br>
      {{  form.surface_area  }} <br><br>
      {{  form.submit    }}
    </form>
  </body>

templates/data/overview_data.html
<!DOCTYPE html>
  <html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Data Dash</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  </head>

  <body>

    <h1>Data Dashboard (to include relevant tables and visualizations)</h1>
    <p> Will include list of users in user database, amount of paints used, amount of products processed, 
      average time spent per product, individual user stats...
    </p>

    <a href="{{url_for('main.logout')}}">Click to log out.</a>
    <h2> USER DATA</h2>
       <table border="1">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Username</th>
            <th>Email Address</th>
            <th>Role</th>
            <th>Edit</th>
        </tr>
        {% for user in users %}
        <tr>
            <form method="POST" action="{{ url_for('main.edit_user', user_id=user.id) }}">
              <td>{{ user.first }}</td>
              <td>{{ user.last }}</td>
              <td>{{ user.username }}</td>
              <td><input type="text" name="email" value="{{ user.email }}"></td>
              <td>{{ user.role }}</td>
              <td>
                <button type="submit" name="action" value="update_email">Update Email</button>
                <button type="submit" name="action" value="toggle_role">Update Role</button>
              </td>
            </form>
        </tr>
        {% endfor %}
    </table>

    <h2> JOB DATA</h2>
    <table border="1">
    <tr>
        <th>ID</th>
        <th>User</th>
        <th>Part Name</th>
        <th>Num Batches</th>
        <th>Num Per Batch</th>
        <th>Task</th>
        <th>Paint Type</th>
        <th>Total Time (s)</th>
        <th>Avg Time/Batch (s)</th>
        <th>Avg Time/Part (s)</th>
        <th>Date</th>
    </tr>
    {% for job in jobs %}
    <tr>
        <td>{{ job.id }}</td>
        <td>{{ job.user.username }}</td>
        <td>{{ job.part_name }}</td>
        <td>{{ job.num_batches }}</td>
        <td>{{ job.num_per_batch }}</td>
        <td>{{ job.task }}</td>
        <td>{{ job.paint_type }}</td>
        <td>{{ job.total_time }}</td>
        <td>{{ job.avg_time_per_batch }}</td>
        <td>{{ job.avg_time_per_part }}</td>
        <td>{{ job.date.strftime('%Y-%m-%d') }}</td>
    </tr>
    {% endfor %}
  </table>

  <h2> PART DATA</h2>
  <table border="1">
    <tr>
        <th>ID</th>
        <th>Part Name</th>
        <th>Surface Area</th>
    </tr>
    {% for part in parts %}
    <tr>
        <td>{{ part.id }}</td>
        <td>{{ part.part_name }}</td>
        <td>{{ part.surface_area }}</td>
    </tr>
    {% endfor %}
  </table>
    
  </body>